# Web Scraping and Introductory Data Analysis

Welcome to Homework 0, where we will delve into web scraping and perform an introductory data analysis. This homework will be a hands-on exercise that will help you become familiar with the process of extracting data from websites and conducting basic statistical analysis. 

## Objectives

By the end of this homework, you will be able to:

1. Set up a Python environment with the necessary libraries for web scraping and data analysis.
2. Write a web scraping script using Beautiful Soup and Selenium to collect data from a website.
3. Sample from the collected dataset and compare the statistics of the sample and the population.
   
## Tasks

1. **Environment Setup**: Install the required libraries such as Beautiful Soup, Selenium, pandas, numpy, matplotlib, and seaborn.

2. **Web Scraping**: Write a script to scrape transaction data from [Etherscan.io](https://etherscan.io/txs). Use Selenium to interact with the website and Beautiful Soup to parse the HTML content.

3. **Data Sampling**: Once the data is collected, create a sample from the dataset. Compare the sample statistics (mean and standard deviation) with the population statistics.


## Deliverables

1. A Jupyter notebook with all the code and explanations.
2. A detailed report on the findings, including the comparison of sample and population statistics.
Note: You can include the report in your notebook.

## Getting Started

Begin by setting up your Python environment and installing the necessary libraries. Then, proceed with the web scraping task, ensuring that you handle any potential issues such as rate limiting. Once you have the data, move on to the data sampling and statistical analysis tasks. 

Remember to document your process and findings in the Jupyter notebook, and to include visualizations where appropriate to illustrate your results. <br>
Good luck, and happy scraping!

## Data Collection (Etherscan)

In this section, we will use web scraping to gather transaction data from the Ethereum blockchain using the Etherscan block explorer. Our objective is to collect transactions from the **last 10 blocks** on Ethereum.

To accomplish this task, we will employ web scraping techniques to extract the transaction data from the Etherscan website. The URL we will be targeting for our data collection is:

[https://etherscan.io/txs](https://etherscan.io/txs)

### Steps

1. **Navigate to the URL**: Use Selenium to open the Etherscan transactions page in a browser.

2. **Locate the Transaction Data**: Identify the HTML elements that contain the transaction data for the specified block range.

3. **Extract the Data**: Write a script to extract the transaction details e.g. Hash, Method, Block, etc.

4. **Handle Pagination**: If the transactions span multiple pages, implement pagination handling to navigate through the pages and collect all relevant transaction data.

5. **Store the Data**: Save the extracted transaction data into a structured format, such as a CSV file or a pandas DataFrame, for further analysis.

### Considerations

- **Rate Limiting**: Be mindful of the website's rate limits to avoid being blocked. Implement delays between requests if necessary.
- **Dynamic Content**: The Etherscan website may load content dynamically. Ensure that Selenium waits for the necessary elements to load before attempting to scrape the data.
- **Data Cleaning**: After extraction, clean the data to remove any inconsistencies or errors that may have occurred during the scraping process.

### Resources

- [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Selenium Documentation](https://selenium-python.readthedocs.io/)
- [Pandas Documentation](https://pandas.pydata.org/docs/)
- [Ethereum](https://ethereum.org/en/)

In [24]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
import pandas as pd

In [55]:
driver = webdriver.Chrome()

url = "https://etherscan.io/txs"

driver.get(url)

In [56]:
body = driver.find_element(By.TAG_NAME,"tbody")
html_content=body.get_attribute("innerHTML")
soup = BeautifulSoup(html_content, "html.parser")

In [57]:
tr=soup.find_all("tr")

In [58]:
all_data = []
block_num=0
while(block_num<50):
    for item in tr:    
        all_data.append(
            {
            "txn Hash": item.find("span", class_="hash-tag").text.strip(),
            "Method": item.find("span", class_="badge").text.strip(),
            "Block": item.find_all("td")[3].text.strip(),
            "Age": item.find("td", class_="showAge").text.strip(),
            "Sender": item.find_all("td")[7].text.strip(),
            "Receiver": item.find_all("td")[9].text.strip(),
            "Value": item.find_all("td")[10].text.strip(),
            "Txn Fee": item.find_all("td", class_="small text-muted showTxnFee")[0].text.strip()
            }
        )
    next_page = driver.find_element(By.XPATH, '//a[@class="page-link px-3" and @aria-label="Next"]')  # Locate the next page link
    # next_page = driver.find_element(By.XPATH, "//a[@aria-label='Next']")
    next_page.click()
    block_num+=1

df = pd.DataFrame(all_data)

In [59]:
display(df)

,txn Hash,Method,Block,Age,Sender,Receiver,Value,Txn Fee
0,0x0937102fc34fc6be03be6b385f864d4ee298ed8f2deb...,Transfer,19334168,13 secs ago,KuCoin 20,RFox: RFOX Token,0 ETH,0.00359686
1,0x7d89d13029389dc99982c6fd06f12e9bfb7336e33d48...,Transfer,19334168,13 secs ago,KuCoin 20,Cronos Coin: CRO Token,0 ETH,0.00373739
2,0x1e2d2b779995a2d02b0e217ad6e8bd8aaaf0a70324ce...,Sell To Uniswap,19334168,13 secs ago,0x3fE7bd51...f0425831a,0x: Exchange Proxy,0 ETH,0.01394318
3,0xfde74a006bfd422e959f89bde370da54770edb202fbb...,Swap,19334168,13 secs ago,0x94Fd126d...0Fb3EAD38,Metamask: Swap Router,0 ETH,0.01586957
4,0x077589427f6ebb4f8a8b81883e540346787eb9c23462...,Transfer,19334168,13 secs ago,0x0084Dfd7...37ca3E95E,dYdX: DYDX Token,0 ETH,0.01184911
...,...,...,...,...,...,...,...,...
2495,0xac91d61b52d3ae70c0489294a8707bbbaaac77fbe1b7...,Execute,19334168,13 secs ago,0x37a2F5cC...e4E20ff9d,Uniswap: Universal Router,0.311 ETH,0.00918097
2496,0x4baa613cd0587d28cac3e65a002ae7f2dd3d516bca83...,Execute,19334168,13 secs ago,0xF872Cbea...5f2D666C3,Uniswap: Universal Router,0.143315732 ETH,0.00897725
2497,0x0545afa5b04e53582b2f6dcea06cee46c00a26e9fa7b...,0x415565b0,19334168,13 secs ago,0x5CFEea92...4C03703af,0x: Exchange Proxy,0.086398064 ETH,0.00976442
2498,0x00d82e1c3c034ec8d60e99b33cf3638ec32647560bdc...,Transfer,19334168,13 secs ago,sleeping.eth,0x69740216...71dbfc524,0.15 ETH,0.01233462
2499,0x490ea5109428d8ab4d8ecf04a9fc293f39001948a57a...,Execute,19334168,13 secs ago,0x9e78E815...9832b4b2a,Uniswap: Universal Router,0 ETH,0.01049042

## Data Analysis

Now that we have collected the transaction data from Etherscan, the next step is to perform conduct an initial analysis. This task will involve the following steps:

1. **Load the Data**: Import the collected transaction data into a pandas DataFrame.

2. **Data Cleaning**: Clean the data by converting data types, removing any irrelevant information, and handling **duplicate** values.

3. **Statistical Analysis**: Calculate the mean and standard deviation of the population. Evaluate these statistics to understand the distribution of transaction values. The analysis and plotting will be on **Txn Fee** and **Value**.

4. **Visualization**: This phase involves the creation of visual representations to aid in the analysis of transaction values. The visualizations include:
    - A histogram for each data column, which provides a visual representation of the data distribution. The selection of bin size is crucial and should be based on the data's characteristics to ensure accurate representation. Provide an explanation on the bin size selection!
    - A normal distribution plot fitted alongside the histogram to compare the empirical distribution of the data with the theoretical normal distribution.
    - A box plot and a violin plot to identify outliers and provide a comprehensive view of the data's distribution.

### Deliverables

The project aims to deliver the following deliverables:

- A refined pandas DataFrame containing the transaction data, which has undergone thorough cleaning and is ready for analysis.
- A simple statistical analysis evaluating the population statistics, offering insights into the distribution of transaction values and fees.
- A set of visualizations showcasing the distribution of transaction values for the population. These visualizations include histograms, normal distribution plots, box plots, and violin plots, each serving a specific purpose in the analysis.

### Getting Started

The project starts with the importing of transaction data into a pandas DataFrame, setting the stage for data manipulation and analysis. Subsequent steps involve the cleaning of the data to ensure its quality and reliability. Followed by the calculation of population statistics. Finally, a series of visualizations are created to visually analyze the distribution of transaction values and fees.

In [7]:
df

,txn Hash,Method,Block,Age,Sender,Receiver,Value,Txn Fee
0,0x7bf7bed01e6b2aa5d4b39c9e630322cb7b33721ada89...,Transfer,19327635,13 secs ago,rsync-builder.eth,Lido: Execution Layer Rewards Vault,0.114458223 ETH,0.00311235
1,0x5872156d4a33216e280b48603e1e36d772477c15b2de...,Sell Eth For Tok...,19327635,13 secs ago,0xF887CA...494cAA02,0x: Exchange Proxy,1.490861762 ETH,0.02171594
2,0x99b5a52c32ef12181f8e3025f4ea07cbbf4ccd0e2a85...,Transfer,19327635,13 secs ago,0x1dE6A1...8459188A,Terra: LUNC Token,0 ETH,0.00662267
3,0xa83dfce0857c092218ac25d51f6f34778aac4b4f5307...,Sell To Uniswap,19327635,13 secs ago,0x83b525...82d1c428,0x: Exchange Proxy,0.869237032 ETH,0.01958003
4,0xbc87f2882f3ce2ba4819d21edd1df7b6c0a89c01b15a...,0x415565b0,19327635,13 secs ago,0x3D079B...5aA6Ea10,0x: Exchange Proxy,0 ETH,0.0310843
...,...,...,...,...,...,...,...,...
495,0xf6eb3dc8cbbb1137e92dbec4db2174b771d28f4a0b4d...,Execute,19327635,13 secs ago,0xeaACA3...66097540,Uniswap: Universal Router,0 ETH,0.03629295
496,0x1b7eade9a46f330249f6709632b63ec0d60c92aaf1a6...,Execute,19327635,13 secs ago,0xA0238C...ea59D570,Uniswap: Universal Router,1.533571077 ETH,0.0254427
497,0x877222f3469385b0b09d716dd809523c5cfec67af746...,Transfer,19327635,13 secs ago,0xe845D4...fF77C1D3,Tether: USDT Stablecoin,0 ETH,0.00889622
498,0x4db841e90e03bdabfe56bc6a489a721e6014eaebefad...,Transfer,19327635,13 secs ago,0xd8F315...a53527A5,Circle: USDC Token,0 ETH,0.00808693
499,0x5376f49a3cb83601e951ca1ae1779c9586e34f7f6d4e...,Approve,19327635,13 secs ago,0x99a516...Ef60230B,ZEN Exchange: ZCX Token,0 ETH,0.0075765

In [8]:
df.dtypes

txn Hash    object
Method      object
Block       object
Age         object
Sender      object
Receiver    object
Value       object
Txn Fee     object
dtype: object

In [36]:
df["txn Hash"] = df["txn Hash"].apply(int , base=16).astype(int)
df

,txn Hash,Method,Block,Age,Sender,Receiver,Value,Txn Fee
0,2202984535579796512119168472978411420202273392...,Transfer,19334035,13 secs ago,rsync-builder.eth,Lido: Execution Layer Rewards Vault,0.064716674 ETH,0.00173425
1,2035318377577241389125259742837315346106953305...,Transfer,19334035,13 secs ago,ravdkmr.eth,0x2cf92152...f935BCC20,0.014 ETH,0.00164713
2,2394472782524524137386784228450350293905986187...,Transfer,19334035,13 secs ago,0x119306f5...5c36CBb25,Illuvium: ILV Token,0 ETH,0.00444805
3,9590979180660875217637722607222708739726146072...,Transfer,19334035,13 secs ago,0xC80eEC4A...fcf71c832,0xe829be6E...39160a23e,0.028797737 ETH,0.00164713
4,3020089774078189686783399700827499035276414462...,Transfer,19334035,13 secs ago,0x449B3D3C...3efBF428E,0x13b9903c...024f1E900,0.003845458 ETH,0.00164713
...,...,...,...,...,...,...,...,...
2495,1472218769934531068167988884170347514902583573...,Relay Tokens,19334035,13 secs ago,0xethics.eth,PulseChain: Omnibridge Proxy,0 ETH,0.01573615
2496,7668158970129579236370925268416352903862060601...,Swap,19334035,13 secs ago,0xDbdd0Fe7...aA9f295f1,Metamask: Swap Router,0.15 ETH,0.01522715
2497,2739669805494172455135406242195947024966115749...,Transfer,19334035,13 secs ago,0xDcFe898D...9380b5aCe,0x2A5DC879...34f54e047,0.04634269 ETH,0.00164805
2498,1615888106752170548441119189786880274137294324...,Transfer,19334035,13 secs ago,0xe51FEFf7...9728d5768,0x69740216...71dbfc524,0.305259522 ETH,0.01169519
2499,3266991349746797467435269684936282364994103458...,Transfer,19334035,13 secs ago,0x1832fe28...5f6044f3A,0x69740216...71dbfc524,0.25 ETH,0.01169519

In [ ]:
unique_df = df.drop_duplicates()
display(unique_df)

In [39]:
uniques = df["Method"].unique()
for i in uniques :
    print (i)

Transfer
Relay
Sell Eth For Tok...
Approve
Take Bid Single
Set Approval For...
Execute
Deposit
Unstake
Cooldown Shares
Relay Tokens
Swap

In [40]:
block_uniques = df["Block"].unique()
for i in block_uniques :
    print (i)

19334035

In [47]:
val_uniques = df["Value"].unique()
for i in val_uniques :
    print (i)

0.064716674 ETH
0.014 ETH
0 ETH
0.028797737 ETH
0.003845458 ETH
0.016825389 ETH
0.000018636 ETH
0.243599772 ETH
0.2 ETH
0.14 ETH
8.65 ETH
0.25 ETH
0.017438631 ETH
0.1 ETH
2.5 ETH
0.014532349 ETH
0.06174936 ETH
0.023132593 ETH
0.15 ETH
0.04 ETH
0.04634269 ETH
0.305259522 ETH

In [54]:
#df['Value'] = df['Value'].str.replace(' ETH', '').astype(float)
df.dtypes

txn Hash     object
Method       object
Block        object
Age          object
Sender       object
Receiver     object
Value       float64
Txn Fee      object
dtype: object

## Data Sampling and Analysis

In this section, we will delve into the process of data sampling and perform an initial analysis on the transaction data we have collected. Our objective is to understand the distribution of transaction values by sampling the data and comparing the sample statistics with the population statistics.

### Steps

1. **Load the Data**: Import the collected transaction data into a pandas DataFrame.

2. **Data Cleaning**: Clean the data by handling missing values, converting data types, and removing any irrelevant information.

3. **Simple Random Sampling (SRS)**: Create a sample from the dataset using a simple random sampling method. This involves randomly selecting a subset of the data without regard to any specific characteristics of the data.

4. **Stratified Sampling**: Create another sample from the dataset using a stratified sampling method. This involves dividing the data into strata based on a specific characteristic (e.g., transaction value) and then randomly selecting samples from each stratum. Explain what you have stratified the data by and why you chose this column.

5. **Statistical Analysis**: Calculate the mean and standard deviation of the samples and the population. Compare these statistics to understand the distribution of transaction values.

6. **Visualization**: Plot the distribution of transaction values and fees for both the samples and the population to visually compare their distributions.

### Considerations

- **Sample Size**: The size of the sample should be large enough to represent the population accurately but not so large that it becomes impractical to analyze.
- **Sampling Method**: Choose the appropriate sampling method based on the characteristics of the data and the research question.

Explain the above considerations in your report.

In [1]:
# Your code here